import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import cases from './fixtures/cubiomes-end-cities.json';

// public/cities.json is generated by `npm run precompute`; it must agree with the reference data.
describe.skipIf(!existsSync('public/cities.json'))('precomputed cities', () => {
  it('contains exactly the reference cities, with the same ship flags, where the two overlap', () => {
    const file = JSON.parse(readFileSync('public/cities.json', 'utf8'));
    const ref = cases.find((c) => c.seed === file.seed && c.regMin < 0)!;
    // The reference covers whole 20-chunk regions; compare inside a box both fully cover.
    const lim = Math.min(-ref.regMin, ref.regMax) * 20 - 20;
    const inBox = (x: number, z: number) => Math.abs(x) < lim && Math.abs(z) < lim;
    const have = new Set<string>();
    for (let i = 0; i < file.cities.length; i += 3) {
      const [x, z, ship] = file.cities.slice(i, i + 3);
      // 2 marks a ship that is a tight fit; the reference only says ship or no ship.
      if (inBox(x, z)) have.add(`${x} ${z} ${ship ? 1 : 0}`);
    }
    const want = new Set(ref.cities.filter(([x, z]) => inBox(x, z)).map(([x, z, s]) => `${x} ${z} ${s}`));
    expect(want.size).toBeGreaterThan(1000);
    expect(have).toEqual(want);
  });
});
